application: dark-passenger
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /static/css/
  static_dir: static/css
- url: /static/js
  static_dir: static/js
- url: /static/js/ui
  static_dir: static/js/ui
- url: /static/images
  static_dir: static/images
- url: /statis/pages
  static_dir: static/pages
- url: /.*
  script: main.py
