application: dark-passenger
version: 1
runtime: python
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
#all images and support file (css, fonts...): return file if found, 
#otherwise the default 404 page so it can be handled by sites that link
#directly to images.
- url: /(.*\.(js|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))
  static_files: static/\1
  upload: static/(.*\.(js|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))  

#all other urls: return the 404 not found 
- url: /.*
  static_files: static/notfound.html 
  upload: static/notfound.html

